"""
compiler.py
WDD Intent Processor module containing the BlueprintEngine.
"""
import os
import json
from datetime import datetime, timezone
import uuid

class BlueprintEngine:
    """
    BlueprintEngine for the 3-pass OB processing logic.
    """
    def __init__(self):
        self.state = "OPEN"
        self.intent = None

    def pass_1(self, raw_prompt):
        """
        Pass 1: Ingest
        Saves the intent immutably. Refuses if intent already exists.
        """
        os.makedirs("docs", exist_ok=True)
        intent_path = "docs/INTENT.md"
        
        if os.path.exists(intent_path):
            with open(intent_path, "r", encoding="utf-8") as f:
                existing = f.read().strip()
                if existing:
                    raise FileExistsError("Immutable intent already exists. Refusing to overwrite.")
                    
        with open(intent_path, "w", encoding="utf-8") as f:
            f.write(f"# RAW INTENT\n\n{raw_prompt}\n\n*Ingested: {datetime.now(timezone.utc).isoformat()}*")
            
        self.intent = raw_prompt
        return intent_path

    def pass_2(self):
        """
        Pass 2: Scaffold
        Generates the HOLEMAP.md based on the intent.
        """
        if not self.intent:
            raise ValueError("Must run pass_1 (Ingest) first.")
            
        os.makedirs("docs", exist_ok=True)
        holemap_path = "docs/HOLEMAP.md"
        
        content = f"""# HOLE MAP
Generated from Intent: {self.intent[:30]}...

| Phase | Grid | Status |
|-------|------|--------|
| P0    | A-01 | HOLE   |
| P1    | B-01 | HOLE   |
"""
        with open(holemap_path, "w", encoding="utf-8") as f:
            f.write(content)
        return holemap_path

    def pass_3(self):
        """
        Pass 3: Fan-out
        Translates the scaffold into concrete Workorder Envelopes.
        """
        wo_id = f"wo-init-{uuid.uuid4().hex[:6]}"
        envelope = {
            "$schema": "https://wdd.jdieselny.com/schemas/workorder.schema.json",
            "workorder_id": wo_id,
            "version": "1.0.0",
            "created_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
            "issuer": "principal_agent_smith",
            "assigned_to": "agent:opus.jdieselny.com",
            "action": "system.init.compile",
            "title": f"Compiled Objective for: {self.intent[:15]}",
            "status": "OPEN",
            "description": "Generated by BlueprintEngine Fan-out.",
            "dependencies": ["wo-032-genesis-seal"],
            "deliverables": ["docs/architecture.md"],
            "requirements": {"stub": "true"},
            "acceptance_criteria": ["Human approval granted."],
            "failure_modes": ["FAIL: N/A"]
        }
        return [envelope]
